### ISSUE TITLE
Basic Climate Control research should depend on Air Conditioning

### ISSUE THREAD

**Issue by watson81** [vasumahesh1/EnhancedTemperatureMod#14]
All buildings in Centralized Climate Control depend upon the research  projects Air Conditioning and either Basic Climate Control or Industrial Climate Control.  The Basic Climate Control research project has only Electricity as its prerequisite. This results in a research graph that could cause confusion to users: you can complete Basic Climate Control research and yet be unable to actually build any climate control.

In the [un-modded research window](https://user-images.githubusercontent.com/2303980/50530945-f6b45700-0ad0-11e9-91e6-7841a9baffcf.png) this is confusing enough, but it becomes worse when a mod such as Fluffy's [Research Tree](https://steamcommunity.com/sharedfiles/filedetails/?id=1266570759) is used. In this case, it incorrectly states that the various climate control buildings are enabled by both the Air Conditioning and the Basic/Industrial Climate Control projects:
![research prerequisites 2](https://user-images.githubusercontent.com/2303980/50530946-f6b45700-0ad0-11e9-9287-8ffb4a5b46bc.png)

I recommend changing building defs to include only a single pre-requisite: either Basic Climate Control or Industrial Climate Control. Then alter the 2 climate control projects to require Air Conditioning as a prerequisite.

**Comment by vasumahesh1** [comment]
@watson81 

Thanks for all the fixes, Can you please confirm the final tests on the mod?

Usually I test two things:
1) New game with mod
2) Old save game with the newer version of the mod

Also might want to test a new test case: Basically, air flowing without the Climate Control unit.

**Comment by watson81** [comment]
I've been playing quite a bit using my local branch, which combines #14 and #15. However, it does not include the other fixes that it looks like you're prepping for release (#7 and #11). Thus, my tests indicate that:
1. New game with mod from the start works fine.
2. Save game with old version of mod loaded using newer version of mod (aka "The Upgrade" test) works fine
3. Save game without any version of the mod loaded with new mod (aka "The New User With Existing Save" test) works fine
4. Removing the CCU causes thermal efficiency to fall to 0, but flow efficiency remains at 100%. Since I'm not using the fix for #7, removing the CCU results in no noticeable ventilation. I.e. pumping ambient air into a generator-heated room doesn't cool it down.

While I was reading #9, I just noticed you ask asl97 to add author info to Misc/Text. Sorry, I didn't see that earlier. If you want to add me there, please direct to https://patrickwatson.org. It's just a couple bug fixes though; it's not like I'm adding a bunch of big features or anything. :)
