### ISSUE TITLE
[B18] Pipe placing deconstructs walls and then places pipes

### ISSUE THREAD

**Issue by frenchiveruti** [vasumahesh1/EnhancedTemperatureMod#2]
Hello, I'm having the issue of pawns deconstructing the wall for placing either pipes or vents.
Here's my modlist:
[Modlist.yxt](https://github.com/UnlimitedHugs/RimworldHugsLib/files/1500145/ModsConfig.txt)

Here's a few captures of the issue:

![bug1](https://user-images.githubusercontent.com/1095997/33216099-3e5556cc-d111-11e7-8029-1643e8c50c46.jpg)
Note that he's going to deconstruct:
![bug2](https://user-images.githubusercontent.com/1095997/33216100-3e921a08-d111-11e7-92f0-4ea1a9ca4efd.jpg)

![bug3](https://user-images.githubusercontent.com/1095997/33216101-3ebad90c-d111-11e7-9c00-8f5f32e265a4.jpg)

**Comment by zkovacs-epam** [comment]
Same here. I have invisible conduits mod, and they too replace walls, so it might be related. Also, you can build a wall on the conduit/pipe later, it's just annoying as hell

**Comment by frenchiveruti** [comment]
The funny thing is that even the vents that go wall mounted have the same issue, you can have floating vents with no walls.

**Comment by frenchiveruti** [comment]
Fixed with vasumahesh1@04ffafecec02923b4f08c82cbfac5bf07e29dba4 .
Just download the source and you'll get a working version, the one in the forums seems to be broken. @zkovacs-epam

**Comment by frenchiveruti** [comment]
~~Be warned that the source is like very big vs the very small package that the mod has.~~
Ok I just forked and left only the mod:
https://github.com/frenchiveruti/CentralizedClimateControlMod/releases

**Comment by vasumahesh1** [comment]
Sorry this was fixed on Steam. I forgot to update Github!

**Comment by vasumahesh1** [comment]
Issue was in this XML:
https://github.com/vasumahesh1/CentralizedClimateControlMod/blob/04ffafecec02923b4f08c82cbfac5bf07e29dba4/Defs/ThingDefs_Buildings/Buildings_Temperature.xml#L118

**Comment by vasumahesh1** [comment]
Update is uploaded to Github. Thanks for spotting this out :)

**Comment by frenchiveruti** [comment]
No problem, thanks for the great mod.

**Comment by frenchiveruti** [comment]
Don't forget to post it on Github!
